// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import {
  resolveDatabaseUrl,
  resolveShadowDatabaseUrl,
} from "./lib/database-url";

const databaseUrl = resolveDatabaseUrl(process.env["DATABASE_URL"]);
const shadowDatabaseUrl = resolveShadowDatabaseUrl(process.env["DATABASE_URL"]);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
    ...(shadowDatabaseUrl ? { shadowDatabaseUrl } : {}),
  },
});
