-- CreateTable
CREATE TABLE "AppSettings" (
    "id" TEXT NOT NULL DEFAULT 'default',
    "companyName" TEXT NOT NULL,
    "companyAddress" TEXT NOT NULL,
    "companyPhone" TEXT NOT NULL,
    "companyEmail" TEXT NOT NULL,
    "appTitle" TEXT NOT NULL,
    "appSubtitle" TEXT NOT NULL,
    "quoteFooterText" TEXT,
    "jobsRoot" TEXT NOT NULL,
    "quotePdfFallbackDir" TEXT NOT NULL,
    "jobSubfolders" JSONB NOT NULL,
    "defaultTaxRate" DECIMAL(6,3) NOT NULL,
    "quoteValidityDays" INTEGER NOT NULL,
    "invoiceDueDays" INTEGER NOT NULL,
    "defaultLeadTime" TEXT,
    "paymentTerms" JSONB NOT NULL,
    "estimators" JSONB NOT NULL,
    "trucks" JSONB NOT NULL,
    "drivers" JSONB NOT NULL,
    "trailers" JSONB NOT NULL,
    "truckCapacityLabel" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AppSettings_pkey" PRIMARY KEY ("id")
);

-- Seed default row
INSERT INTO "AppSettings" (
    "id",
    "companyName",
    "companyAddress",
    "companyPhone",
    "companyEmail",
    "appTitle",
    "appSubtitle",
    "quoteFooterText",
    "jobsRoot",
    "quotePdfFallbackDir",
    "jobSubfolders",
    "defaultTaxRate",
    "quoteValidityDays",
    "invoiceDueDays",
    "defaultLeadTime",
    "paymentTerms",
    "estimators",
    "trucks",
    "drivers",
    "trailers",
    "truckCapacityLabel",
    "updatedAt"
) VALUES (
    'default',
    'Long Island Precast',
    '20 Stiriz Road, Brookhaven, NY 11719',
    '(631) 286-0240',
    'nick@li-precast.com',
    'Precast Ops',
    'Quoting & Inventory',
    E'Thank you for the opportunity to quote your project.\nThis quote is valid until the expiration date shown above.',
    'C:\PrecastJobs',
    'C:\PrecastGeneratedPDFs\Quotes',
    '["01 Construction Plans","02 Quotes","03 Submittals","04 Invoices","05 Delivery Tickets","06 Photos","07 Purchase Orders","08 Production","09 Cut Sheets","99 Misc"]'::jsonb,
    8.625,
    30,
    30,
    NULL,
    '["Standard Precast Terms","Net 30","50% Deposit / Balance on Delivery"]'::jsonb,
    '["Nick","Mike"]'::jsonb,
    '["Truck 1","Truck 3","Lowboy"]'::jsonb,
    '["Mike","Anthony","TBD"]'::jsonb,
    '["Flatbed Trailer","Lowboy Trailer","None"]'::jsonb,
    '80,000 lb',
    CURRENT_TIMESTAMP
) ON CONFLICT ("id") DO NOTHING;
