import { getCompanyProfile } from "@/lib/app-settings";

export type SubmittalCoverProduct = {
  productCode: string;
  productName: string;
  documentNames: string[];
};

export type SubmittalCoverData = {
  quoteNumber: string;
  customerName: string;
  projectName: string;
  quoteDate: string;
  products: SubmittalCoverProduct[];
  missingProducts: string[];
};

export async function buildSubmittalCoverHtml(data: SubmittalCoverData) {
  const company = await getCompanyProfile();

  const productRows = data.products
    .map(
      (product) => `
        <tr>
          <td>${escapeHtml(product.productCode)}</td>
          <td>${escapeHtml(product.productName)}</td>
          <td>${escapeHtml(product.documentNames.join(", ") || "—")}</td>
        </tr>
      `,
    )
    .join("");

  const missingBlock =
    data.missingProducts.length > 0
      ? `<p class="missing"><strong>Missing submittals:</strong> ${escapeHtml(data.missingProducts.join(", "))}</p>`
      : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Submittal Package ${escapeHtml(data.quoteNumber)}</title>
  <style>
    body { font-family: Arial, sans-serif; color: #111827; margin: 0; padding: 32px; }
    h1 { font-size: 24px; margin: 0 0 8px; }
    .meta { color: #4b5563; font-size: 13px; margin-bottom: 24px; }
    table { width: 100%; border-collapse: collapse; font-size: 12px; margin-top: 16px; }
    th, td { border: 1px solid #d1d5db; padding: 8px; text-align: left; vertical-align: top; }
    th { background: #f3f4f6; }
    .missing { margin-top: 20px; color: #b45309; font-size: 12px; }
    .footer { margin-top: 32px; font-size: 11px; color: #6b7280; }
  </style>
</head>
<body>
  <h1>Submittal Package</h1>
  <div class="meta">
    <div><strong>${escapeHtml(company.name)}</strong></div>
    <div>Quote ${escapeHtml(data.quoteNumber)} · ${escapeHtml(data.quoteDate)}</div>
    <div>${escapeHtml(data.customerName)} — ${escapeHtml(data.projectName)}</div>
  </div>
  <table>
    <thead>
      <tr>
        <th>Product Code</th>
        <th>Product</th>
        <th>Included Documents</th>
      </tr>
    </thead>
    <tbody>
      ${productRows || `<tr><td colspan="3">No submittal documents included.</td></tr>`}
    </tbody>
  </table>
  ${missingBlock}
  <p class="footer">Generated by Precast Ops</p>
</body>
</html>`;
}

function escapeHtml(value: string) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}
